# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
#- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Archivo', path: 'menu', url: 'writing.html'}
- {name: 'Materias', path: 'menu', url: 'subjects.html'}
- {name: 'Programas', path: 'menu', url: 'programas.html'}
- {name: 'Prácticas', path: 'menu', url: 'practicas.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/santiagotrini'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:santiagotrini@gmail.com'}
#- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Siguientes'
  previous_page: 'Anteriores'

sharing_button_prompt: 'Compartir en'

related_posts: 'También te puede interesar'

post_date_prefix: 'Escrito el'
